
services:
  mysql:
    image: mysql:latest
    environment: # Changez par rapport a vos informations pour que ça marche
      MYSQL_ROOT_PASSWORD: Pa$w0rd
      MYSQL_DATABASE: wordpress
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network


  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment: # Changez par rapport a vos informations pour que ça marche
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Pa$w0rd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app/wordpress/wp-content:/var/www/html/wp-content
      - ./config/wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - app-network

networks:
  app-network:
    driver: bridge